@ECommerce.WebApi.System_HostAddress = https://localhost:7042

GET {{ECommerce.WebApi.System_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ECommerce.WebApi.System_HostAddress}}/api/categories/6


###

GET {{ECommerce.WebApi.System_HostAddress}}/api/products

###
